In [1]:
## Importing the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

In [3]:
from google.colab import drive
drive.mount('/content/drive')
path=('/content/Train_dataset_(1)_(1)_(2)_(1).csv')
traindata=pd.read_csv(path)

Mounted at /content/drive


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
## Checking the shape of train data
traindata.shape

(3493, 34)

In [6]:
traindata.isnull().sum()

Registration Number                 0
Annual Turnover                     0
Cuisine                             0
City                                0
Restaurant Location                 0
Opening Day of Restaurant           0
Facebook Popularity Quotient       99
Endorsed By                         0
Instagram Popularity Quotient      56
Fire Audit                          0
Liquor License Obtained             0
Situated in a Multi Complex         0
Dedicated Parking                   0
Open Sitting Available              0
Resturant Tier                     49
Restaurant Type                     0
Restaurant Theme                    0
Restaurant Zomato Rating            0
Restaurant City Tier                0
Order Wait Time                     0
Staff Responsivness                 0
Value for Money                     0
Hygiene Rating                      0
Food Rating                         0
Overall Restaurant Rating         212
Live Music Rating                 765
Comedy Gigs Rating               2483
Value Deals Rating               2707
Live Sports Rating               3288
Ambience                           25
Lively                              0
Service                             0
Comfortablility                     0
Privacy                             0
dtype: int64

In [65]:
traindata['Comedy Gigs Rating']=traindata['Comedy Gigs Rating'].fillna(traindata['Comedy Gigs Rating'].mean())
traindata['Overall Restaurant Rating']=traindata['Overall Restaurant Rating'].fillna(traindata['Overall Restaurant Rating'].mean())
traindata['Instagram Popularity Quotient']=traindata['Instagram Popularity Quotient'].fillna(traindata['Instagram Popularity Quotient'].mean())
traindata['Facebook Popularity Quotient']=traindata['Facebook Popularity Quotient'].fillna(traindata['Facebook Popularity Quotient'].mean())
traindata['Live Music Rating']=traindata['Live Music Rating'].fillna(traindata['Live Music Rating'].mean())
traindata['Value Deals Rating']=traindata['Value Deals Rating'].fillna(traindata['Value Deals Rating'].mean())
traindata['Live Sports Rating']=traindata['Live Sports Rating'].fillna(traindata['Live Sports Rating'].mean())


In [66]:
traindata.isnull().sum()

Registration Number               0
Annual Turnover                   0
Cuisine                           0
City                              0
Restaurant Location               0
Opening Day of Restaurant         0
Facebook Popularity Quotient      0
Endorsed By                       0
Instagram Popularity Quotient     0
Fire Audit                        0
Liquor License Obtained           0
Situated in a Multi Complex       0
Dedicated Parking                 0
Open Sitting Available            0
Resturant Tier                   49
Restaurant Type                   0
Restaurant Theme                  0
Restaurant Zomato Rating          0
Restaurant City Tier              0
Order Wait Time                   0
Staff Responsivness               0
Value for Money                   0
Hygiene Rating                    0
Food Rating                       0
Overall Restaurant Rating         0
Live Music Rating                 0
Comedy Gigs Rating                0
Value Deals Rating                0
Live Sports Rating                0
Ambience                         25
Lively                            0
Service                           0
Comfortablility                   0
Privacy                           0
dtype: int64

In [67]:
## Declaring the Linear Regression function

LR = LinearRegression()

In [68]:
## Assigning column to a variable
Insta=traindata[['Instagram Popularity Quotient']]

In [69]:
## Assigning column to a variable
FB=traindata[['Facebook Popularity Quotient']]

In [70]:
## Assigning column to a variable
Sports=traindata[['Live Sports Rating']]

In [71]:
## Assigning column to a variable
Deals=traindata[['Value Deals Rating']]

In [72]:
## Assigning column to a variable
Music=traindata[['Live Music Rating']]

In [73]:
## Assigning column to a variable
Comedy=traindata[['Comedy Gigs Rating']]

In [74]:
## Assigning column to a variable
Overall=traindata[['Overall Restaurant Rating']]

In [196]:
food=traindata[['Food Rating']]

In [197]:
foodmodel = LR.fit(food,traindata['Annual Turnover'])
foodmodel

LinearRegression()

In [198]:
foodmodel.score(food,traindata['Annual Turnover'])

9.130227995868267e-08

In [199]:
foodprediction = foodmodel.predict(testdata[['Food Rating']])
foodprediction

array([30727520.92584267, 30727520.92584267, 30731318.52270437,
       30731318.52270437, 30727520.92584267, 30727520.92584267,
       30735116.11956608, 30731318.52270437, 30727520.92584267,
       30731318.52270437, 30723723.32898097, 30731318.52270437,
       30716128.13525756, 30735116.11956608, 30731318.52270437,
       30716128.13525756, 30723723.32898097, 30727520.92584267,
       30735116.11956608, 30727520.92584267, 30719925.73211927,
       30731318.52270437, 30731318.52270437, 30716128.13525756,
       30731318.52270437, 30731318.52270437, 30716128.13525756,
       30735116.11956608, 30719925.73211927, 30716128.13525756,
       30727520.92584267, 30727520.92584267, 30719925.73211927,
       30719925.73211927, 30723723.32898097, 30731318.52270437,
       30716128.13525756, 30727520.92584267, 30723723.32898097,
       30719925.73211927, 30716128.13525756, 30727520.92584267,
       30716128.13525756, 30723723.32898097, 30723723.32898097,
       30727520.92584267, 30723723.32898

In [137]:
## Simple linear regression with one variable at a time and model score
instamodel = LR.fit(Insta,traindata['Annual Turnover'])
instamodel

LinearRegression()

In [138]:
##model score
instamodel.score(Insta,traindata['Annual Turnover'])

0.026482712263984687

In [139]:
## Using the model built on the Training set to predict on the Test Set

instaprediction = instamodel.predict(testdata[['Instagram Popularity Quotient']])
instaprediction

array([28970960.71768262, 37737095.60304943, 34490378.9788395 ,
       30724187.69475599, 34639727.94355316, 25759957.976339  ,
       23906082.78391513, 27347602.40557766, 31243662.35462957,
       27448250.62092816, 30399516.03233499, 33711166.98902912,
       35139722.30368149, 31081326.52341907, 29078102.36628155,
       27724221.53398601, 33776101.32151332, 27867077.06545124,
       34165707.31641851, 28191748.72787224, 28646289.05526163,
       33516363.99157652, 27996945.73041964, 27996945.73041964,
       31935212.99558628, 26308653.08583048, 36373474.62088126,
       35139722.30368149, 32996889.33170294, 35789065.62852347,
       27120332.24188296, 31243662.35462957, 36146204.45718656,
       36535810.45209175, 31243662.35462957, 22802199.13168375,
       32542349.00431354, 29490435.37755621, 28743690.55398792,
       24360623.11130452, 36730613.44954436, 27802142.73296705,
       29321606.11309729, 27802142.73296705, 35983868.62597607,
       31568334.01705056, 27672274.06799

In [170]:
## Simple linear regression with one variable at a time
fbmodel = LR.fit(FB,traindata['Annual Turnover'])
fbmodel

LinearRegression()

In [171]:
##model score
fbmodel.score(FB,traindata['Annual Turnover'])

0.026429952241711296

In [172]:
## Using the model built on the Training set to predict on the Test Set

fbprediction = fbmodel.predict(testdata[['Facebook Popularity Quotient']])
fbprediction

array([30747972.95902295, 34805978.66546147, 32927743.25791562,
       31249320.12776826, 33171150.94129197, 26697233.15358073,
       30457336.91917059, 24935252.16197582, 32419130.18817399,
       23543832.12118266, 32985870.46588609, 35943092.17138381,
       34380923.4571774 , 31707071.89053572, 33592573.19907789,
       34613432.28905928, 35034854.5468452 , 27115022.46086849,
       32564448.20810017, 25443865.23171744, 30747972.95902295,
       35470808.60662374, 25298547.21179126, 27841612.56049938,
       32927743.25791562, 25516524.24168053, 34925866.03190057,
       30021382.85939205, 33218379.29776797, 35470808.60662374,
       28204907.61031483, 30747972.95902295, 34417252.96215895,
       29959622.70092343, 31837858.10846928, 26025137.31142215,
       30261157.59227025, 28513708.40265795, 30094041.86935515,
       23373083.4477694 , 34526241.47710358, 26461091.37120069,
       27598204.87712303, 25178659.84535217, 34017628.40736195,
       26025137.31142215, 22755481.86308

In [173]:
## Simple linear regression with one variable at a time
sportsmodel = LR.fit(Sports,traindata['Annual Turnover'])
sportsmodel

LinearRegression()

In [174]:
##model score
sportsmodel.score(Sports,traindata['Annual Turnover'])

0.0017663027646421803

In [175]:
sportsprediction = sportsmodel.predict(testdata[['Live Sports Rating']])
sportsprediction

array([31138638.62180356, 40735245.05020723, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 36581490.02895788, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 32427735.00770853,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180356, 31138638.62180356,
       31138638.62180356, 31138638.62180

In [161]:
## Simple linear regression with one variable at a time
dealsmodel = LR.fit(Deals,traindata['Annual Turnover'])
dealsmodel

LinearRegression()

In [162]:
##model score
dealsmodel.score(Deals,traindata['Annual Turnover'])

0.0018760350433264517

In [186]:
## Simple linear regression with one variable at a time
musicmodel = LR.fit(Music,traindata['Annual Turnover'])
musicmodel

LinearRegression()

In [187]:
##model score
musicmodel.score(Music,traindata['Annual Turnover'])

0.025179263372954175

In [188]:
musicprediction = musicmodel.predict(testdata[['Live Music Rating']])
musicprediction

array([30802124.85669966, 26823367.39335234, 26823367.39335234,
       38382093.45475551, 30802124.85669966, 30676276.08048673,
       30676276.08048673, 30676276.08048673, 26823367.39335234,
       30676276.08048673, 30802124.85669966, 26823367.39335234,
       22970458.70621796, 30802124.85669966, 30802124.85669966,
       34529184.76762111, 34529184.76762111, 30676276.08048673,
       34529184.76762111, 30676276.08048673, 22970458.70621796,
       34529184.76762111, 26823367.39335234, 30676276.08048673,
       30676276.08048673, 26823367.39335234, 30676276.08048673,
       34529184.76762111, 30802124.85669966, 26823367.39335234,
       38382093.45475551, 38382093.45475551, 26823367.39335234,
       30676276.08048673, 30802124.85669966, 30676276.08048673,
       34529184.76762111, 34529184.76762111, 30802124.85669966,
       30676276.08048673, 26823367.39335234, 30676276.08048673,
       30802124.85669966, 26823367.39335234, 30676276.08048673,
       30676276.08048673, 30802124.85669

In [165]:
## Simple linear regression with one variable at a time
comedymodel = LR.fit(Comedy,traindata['Annual Turnover'])
comedymodel

LinearRegression()

In [166]:
##model score
comedymodel.score(Comedy,traindata['Annual Turnover'])

0.002882638372257773

In [176]:
## Simple linear regression with one variable at a time
overallmodel = LR.fit(Overall,traindata['Annual Turnover'])
overallmodel

LinearRegression()

In [177]:
#model score
overallmodel.score(Overall,traindata['Annual Turnover'])

0.012792477714576922

In [178]:
overallprediction = overallmodel.predict(testdata[['Overall Restaurant Rating']])
overallprediction

array([25858785.75388272, 31747552.95491369, 25858785.75388272,
       31747552.95491369, 30707119.83713497, 33710475.35525735,
       33710475.35525735, 33710475.35525735, 31747552.95491369,
       25858785.75388272, 31747552.95491369, 29784630.55457003,
       31747552.95491369, 27821708.15422638, 27821708.15422638,
       31747552.95491369, 31747552.95491369, 33710475.35525735,
       31747552.95491369, 33710475.35525735, 30707119.83713497,
       31747552.95491369, 27821708.15422638, 27821708.15422638,
       33710475.35525735, 29784630.55457003, 29784630.55457003,
       31747552.95491369, 27821708.15422638, 33710475.35525735,
       31747552.95491369, 31747552.95491369, 27821708.15422638,
       29784630.55457003, 27821708.15422638, 33710475.35525735,
       31747552.95491369, 31747552.95491369, 29784630.55457003,
       29784630.55457003, 33710475.35525735, 29784630.55457003,
       31747552.95491369, 29784630.55457003, 29784630.55457003,
       33710475.35525735, 31747552.95491

# Loading the Test Data and using the Test Data to Predict the target Variable

In [111]:
testdata= pd.read_csv('/content/Test_dataset_(1)_(1)_(2)_(1).csv')
testdata.head()

Registration Number           Cuisine       City Restaurant Location  \
0                20001   tibetan,italian  Bangalore   Near Business Hub   
1                20002   tibetan,italian  Hyderabad      Near Party Hub   
2                20003  algerian,belgian  Hyderabad      Near Party Hub   
3                20004     tibetan,greek         -1      Near Party Hub   
4                20005     cuban,british      Pune       Near Party Hub   

  Opening Day of Restaurant  Facebook Popularity Quotient      Endoresed By  \
0                13-07-2010                         78.00  Tier A Celebrity   
1                05-09-2011                         89.17      Not Specific   
2                12-04-2011                         84.00      Not Specific   
3                16-01-2005                         79.38      Not Specific   
4                10-11-2008                         84.67      Not Specific   

   Instagram Popularity Quotient  Fire Audit  Liquor License Obtained  ...  \
0                          69.00           1                        1  ...   
1                          96.00           1                        1  ...   
2                          86.00           1                        1  ...   
3                          74.40           0                        1  ...   
4                          86.46           1                        1  ...   

   Overall Restaurant Rating  Live Music Rating  Comedy Gigs Rating  \
0                        6.0                NaN                 2.0   
1                        9.0                3.0                 NaN   
2                        6.0                3.0                 NaN   
3                        9.0                6.0                 NaN   
4                        NaN                NaN                 NaN   

   Value Deals Rating Live Sports Rating Ambience  Lively  Service  \
0                 NaN                NaN        5       2        2   
1                 NaN                6.0        7       8        5   
2                 NaN                NaN        9       7        5   
3                 NaN                NaN        6       7        6   
4                 NaN                NaN        4       4        7   

   Comfortablility  Privacy  
0                6        0  
1                1        8  
2                1        5  
3                4        7  
4                7        3  

[5 rows x 33 columns]

In [112]:
## Checking for the null values

testdata.isnull().sum()

Registration Number                0
Cuisine                            0
City                               0
Restaurant Location                0
Opening Day of Restaurant          0
Facebook Popularity Quotient       0
Endoresed By                       0
Instagram Popularity Quotient      0
Fire Audit                         0
Liquor License Obtained            0
Situated in a Multi Complex        0
Dedicated Parking                  0
Open Sitting Available             0
Resturant Tier                     0
Restaurant Type                    0
Restaurant Theme                   0
Restaurant Zomato Rating           0
Restaurant City Tier               0
Order Wait Time                    0
Staff Responsivness                0
Value for Money                    0
Hygiene Rating                     0
Food Rating                        0
Overall Restaurant Rating         34
Live Music Rating                102
Comedy Gigs Rating               370
Value Deals Rating               385
Live Sports Rating               471
Ambience                           0
Lively                             0
Service                            0
Comfortablility                    0
Privacy                            0
dtype: int64

In [113]:
testdata['Comedy Gigs Rating']=testdata['Comedy Gigs Rating'].fillna(testdata['Comedy Gigs Rating'].mean())
testdata['Overall Restaurant Rating']=testdata['Overall Restaurant Rating'].fillna(testdata['Overall Restaurant Rating'].mean())
testdata['Live Music Rating']=testdata['Live Music Rating'].fillna(testdata['Live Music Rating'].mean())
testdata['Value Deals Rating']=testdata['Value Deals Rating'].fillna(testdata['Value Deals Rating'].mean())
testdata['Live Sports Rating']=testdata['Live Sports Rating'].fillna(testdata['Live Sports Rating'].mean())
testdata['Instagram Popularity Quotient']=testdata['Instagram Popularity Quotient'].fillna(testdata['Instagram Popularity Quotient'].mean())
testdata['Facebook Popularity Quotient']=testdata['Facebook Popularity Quotient'].fillna(testdata['Facebook Popularity Quotient'].mean())

In [114]:
testdata.isnull().sum()

Registration Number              0
Cuisine                          0
City                             0
Restaurant Location              0
Opening Day of Restaurant        0
Facebook Popularity Quotient     0
Endoresed By                     0
Instagram Popularity Quotient    0
Fire Audit                       0
Liquor License Obtained          0
Situated in a Multi Complex      0
Dedicated Parking                0
Open Sitting Available           0
Resturant Tier                   0
Restaurant Type                  0
Restaurant Theme                 0
Restaurant Zomato Rating         0
Restaurant City Tier             0
Order Wait Time                  0
Staff Responsivness              0
Value for Money                  0
Hygiene Rating                   0
Food Rating                      0
Overall Restaurant Rating        0
Live Music Rating                0
Comedy Gigs Rating               0
Value Deals Rating               0
Live Sports Rating               0
Ambience                         0
Lively                           0
Service                          0
Comfortablility                  0
Privacy                          0
dtype: int64

# Saving the output in a data frame and then exporting it to a '.csv' file with the appropriate 'Registration Number'.

In [179]:
solution_df = pd.DataFrame(testdata['Registration Number'])
solution_df['Annual Turnover'] = instaprediction

In [180]:
## Setting the directory to export the file as a '.csv'
import os
os.chdir('/content/drive/My Drive/')

In [181]:
## Exporting the data frame to a '.csv' file and setting the index = False as we do want the index

solution_df.to_csv('Submission.csv',index=False)

In [182]:
solution_df = pd.DataFrame(testdata['Registration Number'])
solution_df['Annual Turnover'] = fbprediction

In [183]:
## Setting the directory to export the file as a '.csv'
import os
os.chdir('/content/drive/My Drive/')

In [184]:
## Exporting the data frame to a '.csv' file and setting the index = False as we do want the index

solution_df.to_csv('Submission1.csv',index=False)

In [189]:
solution_df = pd.DataFrame(testdata['Registration Number'])
solution_df['Annual Turnover'] = musicprediction

In [190]:
## Setting the directory to export the file as a '.csv'
import os
os.chdir('/content/drive/My Drive/')

In [191]:
## Exporting the data frame to a '.csv' file and setting the index = False as we do want the index

solution_df.to_csv('Submission2.csv',index=False)

In [192]:
solution_df = pd.DataFrame(testdata['Registration Number'])
solution_df['Annual Turnover'] = overallprediction

In [193]:
## Setting the directory to export the file as a '.csv'
import os
os.chdir('/content/drive/My Drive/')

In [194]:
## Exporting the data frame to a '.csv' file and setting the index = False as we do want the index

solution_df.to_csv('Submission3.csv',index=False)

In [200]:
solution_df = pd.DataFrame(testdata['Registration Number'])
solution_df['Annual Turnover'] = foodprediction

In [201]:
## Setting the directory to export the file as a '.csv'
import os
os.chdir('/content/drive/My Drive/')

In [202]:
## Exporting the data frame to a '.csv' file and setting the index = False as we do want the index

solution_df.to_csv('Submission4.csv',index=False)

# END